// The third question is: "WHAT SHOULD HAPPEN FOR YOU TO BE HAPPY?"

import cohere from 'cohere-ai';
import * as dotenv from 'dotenv';

dotenv.config();

const classifyThirdQuestion = async (answer: string): Promise<string> => {
  cohere.init(process.env.COHERE_API_KEY);

  const response = await cohere.classify({
    model: 'large',
    inputs: [answer],
    examples: [
      { text: 'reaching goals', label: 'Achiever' },
      { text: 'achieving success', label: 'Achiever' },
      { text: 'winning', label: 'Achiever' },
      { text: 'making progress', label: 'Achiever' },
      { text: 'overcoming challenges', label: 'Achiever' },
      { text: 'gaining recognition', label: 'Achiever' },
      { text: 'achieving status', label: 'Achiever' },
      { text: 'gaining power', label: 'Achiever' },
      { text: 'accumulating wealth', label: 'Achiever' },
      { text: 'being productive', label: 'Achiever' },
      { text: 'completing tasks', label: 'Achiever' },
      { text: 'finishing projects', label: 'Achiever' },
      { text: 'growing skillset', label: 'Achiever' },
      { text: 'overcoming personal obstacles', label: 'Achiever' },
      { text: 'leading a team to success', label: 'Achiever' },
      { text: 'succeeding in difficult situations', label: 'Achiever' },
      { text: 'being the best in their field', label: 'Achiever' },
      { text: 'pushing boundaries', label: 'Achiever' },
      { text: 'setting new records', label: 'Achiever' },
      { text: 'continuing to improve', label: 'Achiever' },
      { text: 'taking charge of their own success', label: 'Achiever' },
      { text: 'discovering new things', label: 'Explorer' },
      { text: 'experiencing new places', label: 'Explorer' },
      { text: 'learning new skills', label: 'Explorer' },
      { text: 'having new adventures', label: 'Explorer' },
      { text: "expanding one's horizons", label: 'Explorer' },
      { text: 'going on a journey', label: 'Explorer' },
      { text: 'exploring the unknown', label: 'Explorer' },
      { text: 'solving mysteries', label: 'Explorer' },
      { text: 'experiencing different cultures', label: 'Explorer' },
      { text: 'having autonomy over their own experience', label: 'Explorer' },
      { text: 'exploring new territories', label: 'Explorer' },
      { text: 'navigating uncharted waters', label: 'Explorer' },
      { text: 'venturing into the unknown', label: 'Explorer' },
      { text: 'pushing boundaries', label: 'Explorer' },
      { text: 'taking risks', label: 'Explorer' },
      { text: 'finding new opportunities', label: 'Explorer' },
      { text: 'uncovering hidden treasures', label: 'Explorer' },
      { text: 'seeking out new experiences', label: 'Explorer' },
      { text: 'daring to try new things', label: 'Explorer' },
      { text: 'embarking on new journeys', label: 'Explorer' },
      { text: 'charting a new course', label: 'Explorer' },
      { text: 'having strong relationships', label: 'Socializer' },
      { text: 'being part of a community', label: 'Socializer' },
      { text: 'connecting with others', label: 'Socializer' },
      { text: 'helping others', label: 'Socializer' },
      { text: 'being appreciated', label: 'Socializer' },
      { text: 'being loved', label: 'Socializer' },
      { text: 'being accepted', label: 'Socializer' },
      { text: 'being valued', label: 'Socializer' },
      { text: 'receiving support', label: 'Socializer' },
      { text: 'feeling a sense of belonging', label: 'Socializer' },
      { text: 'forming meaningful connections', label: 'Socializer' },
      { text: 'creating positive experiences with others', label: 'Socializer' },
      { text: 'being a source of support for others', label: 'Socializer' },
      { text: 'having a supportive network', label: 'Socializer' },
      { text: 'experiencing joy and laughter with others', label: 'Socializer' },
      { text: 'building lasting memories with loved ones', label: 'Socializer' },
      { text: 'enjoying shared experiences', label: 'Socializer' },
      { text: 'participating in group activities', label: 'Socializer' },
      { text: 'sharing personal interests with others', label: 'Socializer' },
      { text: 'having a fulfilling social life', label: 'Socializer' },
      { text: 'winning', label: 'Killer' },
      { text: 'dominating', label: 'Killer' },
      { text: 'being in control', label: 'Killer' },
      { text: 'having power', label: 'Killer' },
      { text: 'defeating enemies', label: 'Killer' },
      { text: 'being feared', label: 'Killer' },
      { text: 'having respect', label: 'Killer' },
      { text: 'having authority', label: 'Killer' },
      { text: 'having influence', label: 'Killer' },
      { text: 'having impact', label: 'Killer' },
      { text: 'conquering obstacles', label: 'Killer' },
      { text: 'exercising dominance', label: 'Killer' },
      { text: 'achieving superiority', label: 'Killer' },
      { text: 'defeating competition', label: 'Killer' },
      { text: 'establishing dominance', label: 'Killer' },
      { text: 'crushing opponents', label: 'Killer' },
      { text: 'taking charge', label: 'Killer' },
      { text: 'exerting power', label: 'Killer' },
      { text: 'enforcing their will', label: 'Killer' },
      { text: 'being the best', label: 'Killer' },
      { text: 'having the upper hand', label: 'Killer' },
    ],
  });

  const classifications = JSON.stringify(response.body.classifications[0].prediction);
  return classifications;
};

export default classifyThirdQuestion;
