// The second question is: "HOW DO YOU LIKE TO SPEND YOUR FREE TIME?"

import cohere from 'cohere-ai';
import * as dotenv from 'dotenv';

dotenv.config();

const classifySecondQuestion = async (answer: string): Promise<string> => {
  cohere.init(process.env.COHERE_API_KEY);

  const response = await cohere.classify({
    model: 'large',
    inputs: [answer],
    examples: [
      { text: 'pursuing personal and professional goals', label: 'Achiever' },
      { text: 'improving skills', label: 'Achiever' },
      { text: 'working on projects', label: 'Achiever' },
      { text: 'setting and achieving challenging targets', label: 'Achiever' },
      { text: 'competing in sports or games', label: 'Achiever' },
      { text: 'exercising', label: 'Achiever' },
      { text: 'planning and organizing', label: 'Achiever' },
      { text: 'reading about successful people and their stories', label: 'Achiever' },
      { text: 'seeking out new opportunities', label: 'Achiever' },
      { text: 'learning new things', label: 'Achiever' },
      { text: 'networking', label: 'Achiever' },
      { text: 'enhancing my reputation', label: 'Achiever' },
      { text: 'achieving recognition', label: 'Achiever' },
      { text: 'getting ahead', label: 'Achiever' },
      { text: 'earning more money', label: 'Achiever' },
      { text: 'managing my finances', label: 'Achiever' },
      { text: 'managing my time effectively', label: 'Achiever' },
      { text: 'gaining expertise in my field', label: 'Achiever' },
      { text: 'promoting my achievements', label: 'Achiever' },
      { text: 'perfecting my skills', label: 'Achiever' },
      { text: 'self-improvement', label: 'Achiever' },
      { text: 'traveling', label: 'Explorer' },
      { text: 'exploring new places', label: 'Explorer' },
      { text: 'trying new things', label: 'Explorer' },
      { text: 'having adventures', label: 'Explorer' },
      { text: 'learning new skills', label: 'Explorer' },
      { text: 'experimenting', label: 'Explorer' },
      { text: 'discovering new cultures', label: 'Explorer' },
      { text: 'being outdoors', label: 'Explorer' },
      { text: 'seeking new experiences and activities', label: 'Explorer' },
      { text: 'going on a journey or a quest', label: 'Explorer' },
      { text: 'taking risks', label: 'Explorer' },
      { text: 'solving puzzles and mysteries', label: 'Explorer' },
      { text: 'collecting unique items and souvenirs', label: 'Explorer' },
      { text: 'trying exotic foods', label: 'Explorer' },
      { text: 'finding hidden treasures', label: 'Explorer' },
      { text: 'hiking and camping', label: 'Explorer' },
      { text: 'surfing and diving', label: 'Explorer' },
      { text: 'exploring nature and wildlife', label: 'Explorer' },
      { text: 'spelunking and caving', label: 'Explorer' },
      { text: 'dabbling in different hobbies', label: 'Explorer' },
      { text: 'competing', label: 'Killer' },
      { text: 'playing and winning games', label: 'Killer' },
      { text: 'practicing combat sports', label: 'Killer' },
      { text: 'watching action movies or playing video games', label: 'Killer' },
      { text: 'strategizing', label: 'Killer' },
      { text: 'planning and analyzing', label: 'Killer' },
      { text: 'seeking out opponents to defeat', label: 'Killer' },
      { text: 'training and improving physical strength', label: 'Killer' },
      { text: 'participating in war games or simulations', label: 'Killer' },
      { text: 'watching sports', label: 'Killer' },
      { text: 'training my mind and body to be the best', label: 'Killer' },
      { text: 'testing my limits in competitive situations', label: 'Killer' },
      { text: 'using strategy to defeat others in competitive scenarios', label: 'Killer' },
      { text: 'participating in friendly challenges and competitions', label: 'Killer' },
      { text: 'joining a team and competing in team-based activities', label: 'Killer' },
      { text: 'competing with oneself to improve personal performance', label: 'Killer' },
      { text: 'engaging in virtual reality and simulation games', label: 'Killer' },
      { text: 'challenging others in games and activities', label: 'Killer' },
      { text: 'pushing oneself to achieve excellence and beat others', label: 'Killer' },
      { text: 'engaging in activities that require strategy and quick thinking', label: 'Killer' },
      { text: 'spending time with friends and family', label: 'Socializer' },
      { text: 'participating in group activities', label: 'Socializer' },
      { text: 'joining clubs and organizations', label: 'Socializer' },
      { text: 'volunteering', label: 'Socializer' },
      { text: 'hosting or attending social gatherings', label: 'Socializer' },
      { text: 'chatting and connecting with others', label: 'Socializer' },
      { text: 'helping others', label: 'Socializer' },
      { text: 'being part of a community', label: 'Socializer' },
      { text: 'participating in cultural events', label: 'Socializer' },
      { text: 'working on group projects', label: 'Socializer' },
      { text: 'engaging in online communities and forums', label: 'Socializer' },
      { text: 'taking part in group excursions and trips', label: 'Socializer' },
      { text: 'meeting new people and making friends', label: 'Socializer' },
      { text: 'networking and forming new relationships', label: 'Socializer' },
      { text: 'attending events and parties with friends and family', label: 'Socializer' },
      { text: 'forming and maintaining close relationships with others', label: 'Socializer' },
      { text: 'participating in team sports or games', label: 'Socializer' },
      { text: 'sharing interests and hobbies with others', label: 'Socializer' },
      { text: 'engaging in community service and helping those in need', label: 'Socializer' },
    ],
  });

  const classifications = JSON.stringify(response.body.classifications[0].prediction);
  return classifications;
};

export default classifySecondQuestion;
