// The fourth question is: "WHAT ARE YOUR GOALS IN LIFE?"

import cohere from 'cohere-ai';
import * as dotenv from 'dotenv';

dotenv.config();

const classifyFourthQuestion = async (answer: string): Promise<string> => {
  cohere.init(process.env.COHERE_API_KEY);

  const response = await cohere.classify({
    model: 'large',
    inputs: [answer],
    examples: [
      { text: 'reaching the top of my chosen field', label: 'Achiever' },
      { text: 'becoming financially successful', label: 'Achiever' },
      { text: 'gaining recognition and status', label: 'Achiever' },
      { text: 'achieving high levels of power and influence', label: 'Achiever' },
      { text: 'building a legacy', label: 'Achiever' },
      { text: 'making a significant impact in my community', label: 'Achiever' },
      { text: 'achieving personal and professional milestones', label: 'Achiever' },
      { text: 'setting and achieving challenging goals', label: 'Achiever' },
      { text: 'becoming the best in my field', label: 'Achiever' },
      { text: 'being known for my achievements and accomplishments', label: 'Achiever' },
      { text: 'making a name for themselves', label: 'Achiever' },
      { text: 'growing my reputation', label: 'Achiever' },
      { text: 'reaching my full potential', label: 'Achiever' },
      { text: 'attaining self-sufficiency and independence', label: 'Achiever' },
      { text: 'achieving a sense of purpose and fulfillment', label: 'Achiever' },
      { text: 'establishing financial security', label: 'Achiever' },
      { text: 'achieving stability and comfort in life', label: 'Achiever' },
      { text: 'leaving a positive legacy for future generations', label: 'Achiever' },
      { text: 'growing and improving professionally', label: 'Achiever' },
      { text: 'acquiring new skills and knowledge', label: 'Achiever' },
      { text: 'achieving long-term goals', label: 'Achiever' },
      { text: 'overcoming personal challenges and obstacles', label: 'Achiever' },
      { text: 'providing for my family and loved ones', label: 'Achiever' },
      { text: 'being a role model for others', label: 'Achiever' },
      { text: 'achieving a sense of accomplishment and satisfaction', label: 'Achiever' },
      { text: 'finding success in my personal and professional life', label: 'Achiever' },
      { text: 'setting a positive example for others to follow', label: 'Achiever' },
      { text: 'achieving a sense of balance and stability in life', label: 'Achiever' },
      { text: 'continuously improving myself', label: 'Achiever' },
      { text: 'discovering new places, cultures, and experiences', label: 'Explorer' },
      { text: 'learning new skills and acquiring knowledge', label: 'Explorer' },
      { text: 'having new adventures and taking risks', label: 'Explorer' },
      { text: 'facing new challenges', label: 'Explorer' },
      { text: 'pushing personal boundaries', label: 'Explorer' },
      { text: 'seeking out new opportunities', label: 'Explorer' },
      { text: 'finding new passions and interests', label: 'Explorer' },
      { text: 'living a life of variety and change', label: 'Explorer' },
      { text: 'being free to pursue my own interests and passions', label: 'Explorer' },
      { text: "expanding one's understanding of the world", label: 'Explorer' },
      { text: 'daring to step into the unknown', label: 'Explorer' },
      { text: 'taking on new challenges', label: 'Explorer' },
      { text: 'adapting to new situations', label: 'Explorer' },
      { text: 'learning from failure and mistakes', label: 'Explorer' },
      { text: 'fostering a sense of curiosity and wonder', label: 'Explorer' },
      { text: 'pushing the limits of my comfort zone', label: 'Explorer' },
      { text: 'finding new ways to express themselves', label: 'Explorer' },
      { text: 'finding a sense of meaning and purpose', label: 'Explorer' },
      { text: 'cultivating a sense of independence and self-reliance', label: 'Explorer' },
      { text: 'breaking out of the mold and being unique', label: 'Explorer' },
      { text: 'encountering new perspectives and worldviews', label: 'Explorer' },
      { text: 'having an impact on the world around them', label: 'Explorer' },
      { text: 'finding my own path in life', label: 'Explorer' },
      { text: 'broadening my horizons', label: 'Explorer' },
      { text: 'expanding my understanding of themselves', label: 'Explorer' },
      { text: 'finding a sense of adventure in life', label: 'Explorer' },
      { text: 'embracing the unknown and the unpredictable', label: 'Explorer' },
      { text: 'finding my own purpose in life', label: 'Explorer' },
      { text: 'dominating', label: 'Killer' },
      { text: 'defeating enemies', label: 'Killer' },
      { text: 'having respect', label: 'Killer' },
      { text: 'having authority', label: 'Killer' },
      { text: 'having influence', label: 'Killer' },
      { text: 'having impact', label: 'Killer' },
      { text: 'being the top in my field', label: 'Killer' },
      { text: 'winning', label: 'Killer' },
      { text: 'being in control', label: 'Killer' },
      { text: 'having power', label: 'Killer' },
      { text: 'being feared', label: 'Killer' },
      { text: 'achieving a sense of dominance and superiority over others', label: 'Killer' },
      { text: 'crushing the competition', label: 'Killer' },
      { text: 'achieving a sense of victory and conquest', label: 'Killer' },
      { text: 'establishing a strong reputation', label: 'Killer' },
      { text: 'gaining control and dominance in personal and professional relationships', label: 'Killer' },
      { text: 'achieving and maintaining high levels of personal and professional power', label: 'Killer' },
      { text: 'having a significant impact on the world and making a lasting legacy', label: 'Killer' },
      { text: 'overcoming obstacles and challenges through strength and determination', label: 'Killer' },
      { text: 'building strong relationships', label: 'Socializer' },
      { text: 'connecting with others', label: 'Socializer' },
      { text: 'helping others', label: 'Socializer' },
      { text: 'making a positive impact on the lives of others', label: 'Socializer' },
      { text: 'being appreciated, loved, and accepted', label: 'Socializer' },
      { text: 'feeling a sense of belonging', label: 'Socializer' },
      { text: 'being part of a community', label: 'Socializer' },
      { text: 'being valued', label: 'Socializer' },
      { text: 'receiving support', label: 'Socializer' },
      { text: 'fostering a sense of connection and community', label: 'Socializer' },
      { text: 'developing deep and meaningful relationships', label: 'Socializer' },
      { text: 'building a strong network of friends and acquaintances', label: 'Socializer' },
      { text: 'fostering a supportive and inclusive community', label: 'Socializer' },
      { text: 'contributing to the well-being of others', label: 'Socializer' },
      { text: 'enhancing the lives of those around them through positivity and support', label: 'Socializer' },
      { text: 'being an active and engaged member of my community', label: 'Socializer' },
      { text: 'creating a supportive and inclusive social network', label: 'Socializer' },
      { text: 'being a positive influence on the lives of those around them', label: 'Socializer' },
      { text: 'fostering a sense of belonging and community through shared experiences and relationships', label: 'Socializer' },
    ],
  });

  const classifications = JSON.stringify(response.body.classifications[0].prediction);
  return classifications;
};

export default classifyFourthQuestion;
