// The first question is: "HOW WOULD YOU DESCRIBE YOURSELF USING A FEW WORDS?"

import cohere from 'cohere-ai';
import * as dotenv from 'dotenv';

dotenv.config();

const classifyFirstQuestion = async (answer: string): Promise<string> => {
  cohere.init(process.env.COHERE_API_KEY);

  const response = await cohere.classify({
    model: 'large',
    inputs: [answer],
    examples: [
      { text: 'driven', label: 'Achiever' },
      { text: 'ambitious', label: 'Achiever' },
      { text: 'successful', label: 'Achiever' },
      { text: 'disciplined', label: 'Achiever' },
      { text: 'hardworking', label: 'Achiever' },
      { text: 'focused', label: 'Achiever' },
      { text: 'motivated', label: 'Achiever' },
      { text: 'goal-oriented', label: 'Achiever' },
      { text: 'organized', label: 'Achiever' },
      { text: 'efficient', label: 'Achiever' },
      { text: 'enthusiastic', label: 'Achiever' },
      { text: 'determined', label: 'Achiever' },
      { text: 'dedicated', label: 'Achiever' },
      { text: 'proactive', label: 'Achiever' },
      { text: 'persistent', label: 'Achiever' },
      { text: 'self-motivated', label: 'Achiever' },
      { text: 'methodical', label: 'Achiever' },
      { text: 'results-oriented', label: 'Achiever' },
      { text: 'reliable', label: 'Achiever' },
      { text: 'self-driven', label: 'Achiever' },
      { text: 'curious', label: 'Explorer' },
      { text: 'open-minded', label: 'Explorer' },
      { text: 'independent', label: 'Explorer' },
      { text: 'innovative', label: 'Explorer' },
      { text: 'experimental', label: 'Explorer' },
      { text: 'fearless', label: 'Explorer' },
      { text: 'knowledgeable', label: 'Explorer' },
      { text: 'resourceful', label: 'Explorer' },
      { text: 'explorative', label: 'Explorer' },
      { text: 'daring', label: 'Explorer' },
      { text: 'inquisitive', label: 'Explorer' },
      { text: 'nonconformist', label: 'Explorer' },
      { text: 'unconventional', label: 'Explorer' },
      { text: 'free-spirited', label: 'Explorer' },
      { text: 'imaginative', label: 'Explorer' },
      { text: 'visionary', label: 'Explorer' },
      { text: 'creative', label: 'Explorer' },
      { text: 'pioneering', label: 'Explorer' },
      { text: 'adventurous', label: 'Explorer' },
      { text: 'open-hearted', label: 'Explorer' },
      { text: 'ruthless', label: 'Killer' },
      { text: 'aggressive', label: 'Killer' },
      { text: 'decisive', label: 'Killer' },
      { text: 'dominant', label: 'Killer' },
      { text: 'powerful', label: 'Killer' },
      { text: 'assertive', label: 'Killer' },
      { text: 'confrontational', label: 'Killer' },
      { text: 'strategic', label: 'Killer' },
      { text: 'cutthroat', label: 'Killer' },
      { text: 'dominating', label: 'Killer' },
      { text: 'persistent', label: 'Killer' },
      { text: 'competitive', label: 'Killer' },
      { text: 'ambitious', label: 'Killer' },
      { text: 'fierce', label: 'Killer' },
      { text: 'determined', label: 'Killer' },
      { text: 'forceful', label: 'Killer' },
      { text: 'driven', label: 'Killer' },
      { text: 'uncompromising', label: 'Killer' },
      { text: 'bold', label: 'Killer' },
      { text: 'relentless', label: 'Killer' },
      { text: 'outgoing', label: 'Socializer' },
      { text: 'sociable', label: 'Socializer' },
      { text: 'helpful', label: 'Socializer' },
      { text: 'cooperative', label: 'Socializer' },
      { text: 'communicative', label: 'Socializer' },
      { text: 'empathetic', label: 'Socializer' },
      { text: 'supportive', label: 'Socializer' },
      { text: 'team-oriented', label: 'Socializer' },
      { text: 'charismatic', label: 'Socializer' },
      { text: 'sharing', label: 'Socializer' },
      { text: 'convivial', label: 'Socializer' },
      { text: 'gregarious', label: 'Socializer' },
      { text: 'extroverted', label: 'Socializer' },
      { text: 'easy-going', label: 'Socializer' },
      { text: 'approachable', label: 'Socializer' },
      { text: 'good-natured', label: 'Socializer' },
      { text: 'altruistic', label: 'Socializer' },
      { text: 'sympathetic', label: 'Socializer' },
      { text: 'warm', label: 'Socializer' },
    ],
  });

  const classifications = JSON.stringify(response.body.classifications[0].prediction);
  return classifications;
};

export default classifyFirstQuestion;
